services:
  loki:
    image: grafana/loki:3.1.2
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/config.yml
      - -ingester.availability-zone=ap-southeast-1c
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki-data:/loki
    environment:
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - loki
    restart: unless-stopped

  tempo:
    container_name: tempo
    image: grafana/tempo:2.6.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
      - "14250"
      - "4317"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
      - AWS_REGION=ap-southeast-1
    restart: on-failure

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.121.0
    command:
      - "--config=/conf/config.yaml"
    volumes:
      - ./otel-collector-config.yaml:/conf/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "8888:8888"
      - "55679:55679"
      - "1777:1777"
    restart: on-failure
    depends_on:
      - tempo

  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms

volumes:
  loki-data:
  grafana-data:
  tempo-data:
  prometheus-data: